//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Two
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupID { get; set; }
        public string SupName { get; set; }
        public string SupAddress { get; set; }
        public string SupPhone { get; set; }
        public Nullable<int> MedicineID { get; set; }
    }
}
